### ISSUE TITLE
Scheduler can be forced to run child orders by ending and restarting the service

### ISSUE THREAD

**Issue by lauwrahoo** [lauwrahoo/ASE-project#2]
Todo: Make scheduler log and check the last time a child order was run successfully (?) and make the next run based on that time so that on startup, we do not automatically run a child order. Currently, we naively run the scheduler on startup, even if the scheduler had just run jobs before it got shut down, resulting in too many jobs run in too short of an interval.

**Comment by amaredia** [comment]
fixed with latest push
