### ISSUE TITLE
Login didn't work in Second Iteration Demo

### ISSUE THREAD

**Issue by by2181** [lauwrahoo/ASE-project#5]
Login didn't work in second iteration demo. Looked like it had something to do with Flask authentication

**Comment by lauwrahoo** [comment]
Seems to work on my computer. Could it be an issue with cookies on Julians?

**Comment by lauwrahoo** [comment]
Jk, works on testing in browser, but pytests doesn't pass it.

**Comment by lauwrahoo** [comment]
Fixed log in and tests.
